root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /login
        permanent: true
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /action
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /action
main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /
oc_user:
    resource: "@OCUserBundle/Resources/config/routing.yml"
    prefix:   /admin/
oc_security:
    path: /login
    defaults: { _controller: OCUserBundle:Security:login }
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
