api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /login
        permanent: true
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /action
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /action
users:
    type:     rest
    resource: OCUserBundle\Controller\UserController
    prefix: /api
famille:
    type:     rest
    resource: MainBundle\Controller\FamilleController
    prefix: /api
Medicament:
    type:     rest
    resource: MainBundle\Controller\FamilleController
    prefix: /api
publicUser:
    type:    rest
    resource: OCUserBundle\Controller\PublicUserController
    prefix: /api
motifs:
    type: rest
    resource: MainBundle\Controller\MotifsController
    prefix: /api
main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /
oc_user:
    resource: "@OCUserBundle/Resources/config/routing.yml"
    prefix:   /admin/
oc_security:
    path: /login
    defaults: { _controller: OCUserBundle:Security:login }
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"