# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    #main.menu_listener:
    #    class: MainBundle\EventListener\MenuBuilderListener
    #    tags:
    #        - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }
    app.form.registration:
        class: OCUserBundle\Form\RegistrationType
        Tags:
            - {name: form.type, alias: app_user_registration}
    admin.Famille:
        class: MainBundle\Admin\FamilleAdmin
        arguments: [~, MainBundle\Entity\Famille, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Famille de médicament}
    admin.Dosage:
        class: MainBundle\Admin\DosageAdmin
        arguments: [~, MainBundle\Entity\Dosage, OCUserBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Dosage}
    admin.TypePraticien:
        class: MainBundle\Admin\TypePraticienAdmin
        arguments: [~, MainBundle\Entity\TypePraticien, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Type de praticien}
    admin.Composant:
        class: MainBundle\Admin\ComposantAdmin
        arguments: [~, MainBundle\Entity\Composant, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Composant}
    admin.Presentation:
        class: MainBundle\Admin\PresentationAdmin
        arguments: [~, MainBundle\Entity\Presentation, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Presentation de médicament}
    admin.Motif:
        class: MainBundle\Admin\MotifAdmin
        arguments: [~, MainBundle\Entity\Motif, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Motif de visite}
    admin.Specialite:
        class: MainBundle\Admin\SpecialiteAdmin
        arguments: [~, MainBundle\Entity\Specialite, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Specialite de praticien}
    admin.TypeIndividu:
        class: MainBundle\Admin\TypeIndividuAdmin
        arguments: [~, MainBundle\Entity\TypeIndividu, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Type d'individu}
    admin.MedConstitution:
        class: MainBundle\Admin\MedConstitutionAdmin
        arguments: [~, MainBundle\Entity\MedConstitution, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Constitution medicament}
    admin.Medicament:
        class: MainBundle\Admin\MedicamentAdmin
        arguments: [~, MainBundle\Entity\Medicament,OCUserBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Medicament}
    admin.Praticien:
        class: MainBundle\Admin\PraticienAdmin
        arguments: [~, MainBundle\Entity\Praticien,OCUserBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Praticien}
    admin.Prescrire:
        class: MainBundle\Admin\PrescrireAdmin
        arguments: [~, MainBundle\Entity\Prescrire,~]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Prescription}
    admin.ActCompl:
            class: MainBundle\Admin\ActComplAdmin
            arguments: [~, MainBundle\Entity\ActCompl, OCUserBundle:CRUD]
            tags:
                - {name: sonata.admin, manager_type: orm, label: Activite complementaire}
    admin.ActRea:
            class: MainBundle\Admin\ActReaAdmin
            arguments: [~, MainBundle\Entity\ActRea,~]
            tags:
                - {name: sonata.admin, manager_type: orm, label: Realisation Activite complementaire}
    admin.User:
            class: OCUserBundle\Admin\UserAdmin
            arguments: [~, OCUserBundle\Entity\User,OCUserBundle:CRUD]
            tags:
                - {name: sonata.admin, manager_type: orm, label: Utilisateurs}
    admin.Fonction:
            class: OCUserBundle\Admin\FonctionAdmin
            arguments: [~, OCUserBundle\Entity\Fonction,OCUserBundle:CRUD]
            tags:
                - {name: sonata.admin, manager_type: orm, label: Fonction}
    admin.Departement:
            class: OCUserBundle\Admin\DepartementAdmin
            arguments: [~, OCUserBundle\Entity\Departement,OCUserBundle:CRUD]
            tags:
                - {name: sonata.admin, manager_type: orm, label: Departement}
    admin.Region:
            class: OCUserBundle\Admin\RegionAdmin
            arguments: [~, OCUserBundle\Entity\Region,OCUserBundle:CRUD]
            tags:
                - {name: sonata.admin, manager_type: orm, label: Region}
    admin.Secteur:
            class: OCUserBundle\Admin\SecteurAdmin
            arguments: [~, OCUserBundle\Entity\Secteur,OCUserBundle:CRUD]
            tags:
                - {name: sonata.admin, manager_type: orm, label: Secteur}
    admin.RapportVisite:
            class: MainBundle\Admin\RapportVisiteAdmin
            arguments: [~, MainBundle\Entity\RapportVisite ,OCUserBundle:CRUD]
            tags:
                - {name: sonata.admin, manager_type: orm, label: Rapport de visite}
    admin.RapportEchant:
            class: MainBundle\Admin\RapportEchantAdmin
            arguments: [~, MainBundle\Entity\RapportEchant ,OCUserBundle:CRUD]
            tags:
                - {name: sonata.admin, manager_type: orm, label: Rapport echantillons}
