# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
services:
    wsse.security.authentication.provider:
        class: OCUserBundle\Security\Authentication\Provider\WsseProvider
        arguments:
           - 'fos_userbundle'
           - '@cache.app'
        public: false
    wsse.security.authentication.listener:
        class: OCUserBundle\Security\Firewall\WsseListener
        arguments: ['@security.token_storage', '@security.authentication.manager']
        public: false
    # DECLARATION DES BLOCK CREER EN TANT QUE SERVICE
    sonata.block.service.stats:
        class: MainBundle\Block\StatsBlockService
        arguments:
            - sonata.block.service.stats
            - "@templating"
            - "@doctrine.orm.entity_manager"
            - "@security.authorization_checker"
            - "@security.token_storage"
        tags:
            - { name: sonata.block }
    sonata.block.service.notif:
            class: MainBundle\Block\NotifBlockService
            arguments:
                - sonata.block.service.stats
                - "@templating"
                - "@doctrine.orm.entity_manager"
                - "@security.authorization_checker"
                - "@security.token_storage"
            tags:
                - { name: sonata.block }
    # DECLARATION DE TOUT LES PANELS D'ADMIN D'ENTITE
    app.form.registration:
        class: OCUserBundle\Form\RegistrationType
        Tags:
            - {name: form.type, alias: app_user_registration}



