# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: OCUserBundle\Form\RegistrationType
        Tags:
            - {name: form.type, alias: app_user_registration}
    admin.category:
        class: OCUserBundle\Admin\CategoryAdmin
        arguments: [~, OCUserBundle\Entity\Category, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Category}
    admin.Famille:
        class: MainBundle\Admin\FamilleAdmin
        arguments: [~, MainBundle\Entity\Famille, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Famille}
    admin.Dosage:
            class: MainBundle\Admin\DosageAdmin
            arguments: [~, MainBundle\Entity\Dosage, ~]
            tags:
                - {name: sonata.admin, manager_type: orm, label: Dosage}
    admin.TypePraticien:
            class: MainBundle\Admin\TypePraticienAdmin
            arguments: [~, MainBundle\Entity\TypePraticien, ~]
            tags:
                - {name: sonata.admin, manager_type: orm, label: TypePraticien}
    admin.Composant:
            class: MainBundle\Admin\ComposantAdmin
            arguments: [~, MainBundle\Entity\Composant, ~]
            tags:
                - {name: sonata.admin, manager_type: orm, label: Composant}
    admin.Presentation:
            class: MainBundle\Admin\PresentationAdmin
            arguments: [~, MainBundle\Entity\Presentation, ~]
            tags:
                - {name: sonata.admin, manager_type: orm, label: Presentation}