<?php

namespace MainBundle\Repository;

/**
 * ActComplRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActComplRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByRealisation($user){

        $query=$this->_em->createQuery(
            'SELECT ac
                      FROM MainBundle:ActCompl ac
                      JOIN ac.acActReal rea 
                      WHERE rea.actReaVisiteur = :user
                      '
        )->setParameters(array(
            'user' => $user
        ));
        return $query->getResult();
    }
    public function findByRealisationForValid($user){
        $query=$this->_em->createQuery(
            'SELECT ac
              FROM MainBundle:ActCompl ac
              JOIN ac.acActReal rea 
              WHERE ac.acStates = :etat AND rea.actReaVisiteur = :usr
                  '
        )->setParameters(array(
            'usr' => $user,
            'etat'=>'VALIDATION_REQUISE'
        ));
        return $query->getResult();
    }
    public function findByRegionForValid($region){
        $query=$this->_em->createQuery(
            'SELECT ac 
                FROM MainBundle:ActCompl ac
                JOIN ac.acActReal rea
                JOIN rea.actReaVisiteur usr
                WHERE ac.acStates = :etat  AND usr.usrRegion = :region
                      '
        )->setParameters(array(
            'region' => $region,
            'etat'=>'VALIDATION_REQUISE'
        ));
        return $query->getResult();
    }
    public function findBySecteur($secteur){
        $query=$this->_em->createQuery(
            'SELECT ac 
                      FROM MainBundle:ActCompl ac
                      JOIN ac.acActReal rea
                      JOIN rea.actReaVisiteur usr
                      WHERE usr.usrSecteur = :secteur
                      '
        )->setParameters(array(
            'secteur' => $secteur
        ));
        return $query->getResult();
    }
    public function findByRegion($region){
        $query=$this->_em->createQuery(
            'SELECT ac 
                      FROM MainBundle:ActCompl ac
                      JOIN ac.acActReal rea
                      JOIN rea.actReaVisiteur usr
                      WHERE usr.usrRegion = :region
                      '
        )->setParameters(array(
            'region' => $region
        ));
        return $query->getResult();
    }

}
