<?php

namespace MainBundle\Repository;

/**
 * ActComplRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActComplRepository extends \Doctrine\ORM\EntityRepository
{
}
