<?php

namespace MainBundle\Repository;

/**
 * ActReaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActReaRepository extends \Doctrine\ORM\EntityRepository
{
}
