<?php

namespace MainBundle\Repository;

/**
 * DosageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DosageRepository extends \Doctrine\ORM\EntityRepository
{
}
