<?php

namespace MainBundle\Repository;

/**
 * FamilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleRepository extends \Doctrine\ORM\EntityRepository
{
}
