<?php

namespace MainBundle\Repository;

/**
 * MedConstitutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedConstitutionRepository extends \Doctrine\ORM\EntityRepository
{
}
