<?php

namespace MainBundle\Repository;

/**
 * MotifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotifRepository extends \Doctrine\ORM\EntityRepository
{
}
