<?php

namespace MainBundle\Repository;

/**
 * PraticienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PraticienRepository extends \Doctrine\ORM\EntityRepository
{
}
