<?php

namespace MainBundle\Repository;

/**
 * PrescrireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrescrireRepository extends \Doctrine\ORM\EntityRepository
{
}
