<?php

namespace MainBundle\Repository;

/**
 * RapportEchantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RapportEchantRepository extends \Doctrine\ORM\EntityRepository
{
}
