<?php

namespace MainBundle\Repository;

/**
 * SpecPossederRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecPossederRepository extends \Doctrine\ORM\EntityRepository
{
}
