<?php

namespace MainBundle\Repository;

/**
 * TypeIndividuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeIndividuRepository extends \Doctrine\ORM\EntityRepository
{
}
