<?php

namespace MainBundle\Repository;

/**
 * TypePraticienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePraticienRepository extends \Doctrine\ORM\EntityRepository
{
}
