services:
#    oc_user.example:
#        class: OCUserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    admin.User:
        class: OCUserBundle\Admin\UserAdmin
        arguments: [~, OCUserBundle\Entity\User, ~]
        tags:
                - {name: sonata.admin, manager_type: orm, label: Utilisateurs}
    admin.Fonction:
            class: OCUserBundle\Admin\FonctionAdmin
            arguments: [~, OCUserBundle\Entity\Fonction,~]
            tags:
                - {name: sonata.admin, manager_type: orm, label: Fonction}
    admin.Departement:
            class: OCUserBundle\Admin\DepartementAdmin
            arguments: [~, OCUserBundle\Entity\Departement,~]
            tags:
                - {name: sonata.admin, manager_type: orm, label: Departement}
    admin.Region:
            class: OCUserBundle\Admin\RegionAdmin
            arguments: [~, OCUserBundle\Entity\Region,~]
            tags:
                - {name: sonata.admin, manager_type: orm, label: Region}
    admin.Secteur:
            class: OCUserBundle\Admin\SecteurAdmin
            arguments: [~, OCUserBundle\Entity\Secteur,~]
            tags:
                - {name: sonata.admin, manager_type: orm, label: Secteur}