api_login:
    type:    rest
    resource: ApiBundle\Controller\DefaultController
    prefix: /
api_rapport:
    type:    rest
    resource: ApiBundle\Controller\RapportVisiteController
    prefix: /
api_activite:
    type:    rest
    resource: ApiBundle\Controller\ActComplController
    prefix: /
api_motif:
    type:    rest
    resource: ApiBundle\Controller\MotifController
    prefix: /
api_praticien:
    type:    rest
    resource: ApiBundle\Controller\PraticienController
    prefix: /
api_medicament:
    type:    rest
    resource: ApiBundle\Controller\MedicamentController
    prefix: /
api_user:
    type:    rest
    resource: ApiBundle\Controller\UserController
    prefix: /

