api_login:
    type:    rest
    resource: ApiBundle\Controller\DefaultController
    prefix: /
api_rapport:
    type:    rest
    resource: ApiBundle\Controller\RapportVisiteController
    prefix: /
api_activite:
    type:    rest
    resource: ApiBundle\Controller\ActComplController
    prefix: /