main_homepage_visiteur:
    path:     /visiteur
    defaults: { _controller: MainBundle:Visiteur:index }
main_homepage_delegue:
    path:     /delegue
    defaults: { _controller: MainBundle:Delegue:index }
main_homepage_responsable:
    path:     /responsable
    defaults: { _controller: MainBundle:Responsable:index }
main_statistique_visiteur:
    path:     /visiteur/statistiques
    defaults: { _controller: MainBundle:Visiteur:index }
main_statistique_delegue:
    path:     /delegue/statistiques
    defaults: { _controller: MainBundle:Delegue:index }
main_statistique_responsable:
    path:     /responsable/statistiques
    defaults: { _controller: MainBundle:Responsable:index }